# Generated by Django 5.1.4 on 2024-12-31 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='food_category_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='foodcategory',
            constraint=models.UniqueConstraint(fields=('seller_obj', 'food_category_name'), name='unique_category'),
        ),
    ]
