# Generated by Django 5.1.4 on 2024-12-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_foodcategory_food_category_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='food',
            constraint=models.UniqueConstraint(fields=('seller_category', 'food_name'), name='unique_food'),
        ),
    ]
