# Generated by Django 5.1.4 on 2025-01-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_food_unique_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategory',
            name='category_image',
            field=models.ImageField(null=True, upload_to='category_images/'),
        ),
    ]
