# Generated by Django 5.1.4 on 2025-01-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_foodcategory_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_cateogory_obj',
            new_name='food_category_obj',
        ),
    ]
